### ISSUE TITLE
Site is being flagged as malicious despite clearing all security audits

### ISSUE THREAD

**Issue by tapjay** [Covid-Mutual-Aid/groups-map#20]
# Issue

We have had multiple reports of users not being able to access the site due to it being flagged as a security risk by AVG, BitBlocker and until recently, Virgin Media. I have checked Google Console and several other threat detection platforms, none of which indicate any security issues. 

The app uses SSL for all requests and is not doing anything unusual that could lead to it being identified as a security concern. The flagged domain is [https://covidmutualaid.cc](https://covidmutualaid.cc).

Images below:

![fbakVFHuDzmKSHKzQrKNngptf638TE6Wgs2YJK1Y6olQSb546CzlZPkQJKghzmwI2YN9ryqqTPiCqzz7Y7-oa9ojxHtuwV5pU0-orhoENwlztMW-NLhd6YkdSRLcLOCyS3_ZwG5dKY88z4n-MZpE=s0-d-e1-ft](https://user-images.githubusercontent.com/2171281/79253961-e8cc4600-7e7b-11ea-8bb7-4e4fe64c8af0.png)

![slack-imgs](https://user-images.githubusercontent.com/2171281/79254093-1f09c580-7e7c-11ea-9df9-9734017d3af1.png)

**Comment by conatus** [comment]
Also on Sky.

![Untitled](https://user-images.githubusercontent.com/317734/79255666-904a7800-7e7e-11ea-88d3-05d91cf6e1fa.png)

**Comment by gavinlove** [comment]
My guess is some automated phishing detection system has decided that your URL is too similar to https://covidmutualaid.org/ and that you are attempting to phish that domain.

**Comment by conatus** [comment]
@gavinlove 

This is a good shout actually, thanks Gavin. There is no reason we can't host it on a sub-domain of the main site presumably @tapjay? 

There may be a couple of issues here. The Virgin Media blocking may be a different issue from the automated AVG response.

**Comment by tapjay** [comment]
@gavinlove Good shout, yes that sounds really plausible. I would have thought given its linked as an iframe from the actual .org site its supposedly trying to phish.. Anyway, something new was learned!

For others looking at this, I have since hosted the site as a mirror.
